### ISSUE TITLE
ERRORS when pushing local source metadata to scratch org

### ISSUE THREAD

**Issue by omarestrada90** [omarestrada90/sfdx-project#1]
When performing the Develop an App with Salesforce CLI and Source Control badge, I get these errors when trying to push files into my scratch org:

$ sfdx force:source:push
PROJECT PATH                                                             ERROR
───────────────────────────────────────────────────────────────────────  ────────────────────────────────────────────────────
force-app\main\default\tabs\Property__c.tab-meta.xml                     Property 'mobileReady' not valid in version 46.0
force-app\main\default\tabs\Broker__c.tab-meta.xml                       Property 'mobileReady' not valid in version 46.0
force-app\main\default\tabs\Sample_Data_Import.tab-meta.xml              Property 'mobileReady' not valid in version 46.0
force-app\main\default\permissionsets\DreamHouse.permissionset-meta.xml  In field: tab - no CustomTab named Broker__c found
force-app\main\default\applications\DreamHouse.app-meta.xml              In field: tab - no CustomTab named Property__c found
ERROR running force:source:push:  Push failed.

Would really appreciate any help,

**Comment by bmarshall1985** [comment]
I suspect you'll be able to just remove the entire line for each of the <mobileReady> tags in each of the erroring tabs (your first 3 errors). The other errors are a cascade from those first ones. 

Let me know if that doesn't work and I can look in to what those tags need to be swapped for int he new version
